baseurl = "https://vladimirparfenov.me"
title = "Vladimir Parfenov"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "Vladimir P."

[markup.highlight]
style = "github-dark"

[params]
  author = "Vladimir Parfenov"
  info = "Engineering Manager / Technical Lead"
  description = "Vladimir Parfenov's personal website"
  keywords = "developer,personal"
  avatarurl = "/images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:parfenov.vladimir.s@gmail.com"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/ParfenovVS/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/vladimir-parfenov/"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 4
  url = "https://www.facebook.com/vladimirparf"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 5
  url = "https://twitter.com/Vladimir_Parf/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "Contact me"
  weight = 3
  url  = "contact/"