name: Deploy Hugo site to Pages

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

permissions: 
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages"
  cancel-in-progress: false

defaults: 
  run: 
    shell: bash

jobs: 
  create-pdf: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install toml
      - name: Run Python Script
        run: python export/make_single_md.py
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf
      - name: Convert Markdown files to PDF
        run: md-to-pdf export/vladimirparfenov.md
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with: 
          name: vladimirparfenov.pdf
          path: export/vladimirparfenov.pdf
          compression-level: 0

  build: 
    runs-on: ubuntu-latest
    env: 
      HUGO_VERSION: 0.120.4
    needs: create-pdf
    steps: 
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Download PDF
        uses: actions/download-artifact@v4
        with: 
          name: vladimirparfenov.pdf
          path: static/pdf
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env: 
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
          --minify \
          --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: ./public

  deploy: 
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
